application:
  api:
    path: wom
spring:
  data:
    mongodb:
      uri: mongodb+srv://womk8s:P%40%40sword%25@cluster0.vqabawo.mongodb.net
      database: wom
      #uri: ${MONGODB_URI}
      #database: ${MONGODB_DATABASE}